name: siddhivinayak_app
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"


dependencies:
  flutter:
    sdk: flutter
    

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  provider: ^6.0.3
  cupertino_icons: ^1.0.2
  youtube_player_flutter: ^9.0.1
  # webviewx: ^0.2.2
  animated_splash_screen: ^1.3.0
  firebase_core: ^2.4.0
  firebase_auth: ^4.2.0
  firebase_storage: ^11.0.10
  cloud_firestore: ^4.3.1
  flutter_riverpod: ^2.1.3
  image_picker: ^0.8.6
  intl: ^0.17.0
  # flutter_local_notifications: ^13.0.0
  cached_network_image: ^3.3.1
  carousel_slider: ^5.0.0
  page_transition: ^2.0.9
  http: ^0.13.6
  firebase_messaging: ^14.6.5
  pod_player: ^0.2.0
 
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
     
     


